// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: vehicle.proto

package server

import (
	"context"

	"vehicle/internal/logic"
	"vehicle/internal/svc"
	"vehicle/vehicle"
)

type VehicleServiceServer struct {
	svcCtx *svc.ServiceContext
	vehicle.UnimplementedVehicleServiceServer
}

func NewVehicleServiceServer(svcCtx *svc.ServiceContext) *VehicleServiceServer {
	return &VehicleServiceServer{
		svcCtx: svcCtx,
	}
}

// 接收云端下发的控制指令
func (s *VehicleServiceServer) ControlVehicle(ctx context.Context, in *vehicle.ControlReq) (*vehicle.ControlResp, error) {
	l := logic.NewControlVehicleLogic(ctx, s.svcCtx)
	return l.ControlVehicle(in)
}

// 供其他服务查询车辆实时状态
func (s *VehicleServiceServer) GetVehicleStatus(ctx context.Context, in *vehicle.ControlReq) (*vehicle.VehicleStatusResp, error) {
	l := logic.NewGetVehicleStatusLogic(ctx, s.svcCtx)
	return l.GetVehicleStatus(in)
}
