// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: vehicle.proto

package server

import (
	"context"

	"vehicle/internal/logic"
	"vehicle/internal/svc"
	"vehicle/vehicle"
)

type VehicleServer struct {
	svcCtx *svc.ServiceContext
	vehicle.UnimplementedVehicleServer
}

func NewVehicleServer(svcCtx *svc.ServiceContext) *VehicleServer {
	return &VehicleServer{
		svcCtx: svcCtx,
	}
}

func (s *VehicleServer) Ping(ctx context.Context, in *vehicle.Request) (*vehicle.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
