// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: vehicle.proto

package vehicle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 车辆控制请求
type ControlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleID     string                 `protobuf:"bytes,1,opt,name=VehicleID,proto3" json:"VehicleID,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty"` // 如 unlock_door, start_engine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlReq) Reset() {
	*x = ControlReq{}
	mi := &file_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlReq) ProtoMessage() {}

func (x *ControlReq) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlReq.ProtoReflect.Descriptor instead.
func (*ControlReq) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *ControlReq) GetVehicleID() string {
	if x != nil {
		return x.VehicleID
	}
	return ""
}

func (x *ControlReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// 车辆控制响应
type ControlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResp) Reset() {
	*x = ControlResp{}
	mi := &file_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResp) ProtoMessage() {}

func (x *ControlResp) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResp.ProtoReflect.Descriptor instead.
func (*ControlResp) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *ControlResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ControlResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 车辆状态查询响应
type VehicleStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleID     string                 `protobuf:"bytes,1,opt,name=VehicleID,proto3" json:"VehicleID,omitempty"`
	Speed         float64                `protobuf:"fixed64,2,opt,name=Speed,proto3" json:"Speed,omitempty"`
	FuelLevel     float64                `protobuf:"fixed64,3,opt,name=FuelLevel,proto3" json:"FuelLevel,omitempty"`
	EngineOn      bool                   `protobuf:"varint,4,opt,name=EngineOn,proto3" json:"EngineOn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleStatusResp) Reset() {
	*x = VehicleStatusResp{}
	mi := &file_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleStatusResp) ProtoMessage() {}

func (x *VehicleStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleStatusResp.ProtoReflect.Descriptor instead.
func (*VehicleStatusResp) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *VehicleStatusResp) GetVehicleID() string {
	if x != nil {
		return x.VehicleID
	}
	return ""
}

func (x *VehicleStatusResp) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *VehicleStatusResp) GetFuelLevel() float64 {
	if x != nil {
		return x.FuelLevel
	}
	return 0
}

func (x *VehicleStatusResp) GetEngineOn() bool {
	if x != nil {
		return x.EngineOn
	}
	return false
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_vehicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

var File_vehicle_proto protoreflect.FileDescriptor

const file_vehicle_proto_rawDesc = "" +
	"\n" +
	"\rvehicle.proto\x12\avehicle\"B\n" +
	"\n" +
	"ControlReq\x12\x1c\n" +
	"\tVehicleID\x18\x01 \x01(\tR\tVehicleID\x12\x16\n" +
	"\x06Action\x18\x02 \x01(\tR\x06Action\"3\n" +
	"\vControlResp\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x05R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\x81\x01\n" +
	"\x11VehicleStatusResp\x12\x1c\n" +
	"\tVehicleID\x18\x01 \x01(\tR\tVehicleID\x12\x14\n" +
	"\x05Speed\x18\x02 \x01(\x01R\x05Speed\x12\x1c\n" +
	"\tFuelLevel\x18\x03 \x01(\x01R\tFuelLevel\x12\x1a\n" +
	"\bEngineOn\x18\x04 \x01(\bR\bEngineOn\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong2\x92\x01\n" +
	"\x0eVehicleService\x12;\n" +
	"\x0eControlVehicle\x12\x13.vehicle.ControlReq\x1a\x14.vehicle.ControlResp\x12C\n" +
	"\x10GetVehicleStatus\x12\x13.vehicle.ControlReq\x1a\x1a.vehicle.VehicleStatusResp26\n" +
	"\aVehicle\x12+\n" +
	"\x04Ping\x12\x10.vehicle.Request\x1a\x11.vehicle.ResponseB\vZ\t./vehicleb\x06proto3"

var (
	file_vehicle_proto_rawDescOnce sync.Once
	file_vehicle_proto_rawDescData []byte
)

func file_vehicle_proto_rawDescGZIP() []byte {
	file_vehicle_proto_rawDescOnce.Do(func() {
		file_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vehicle_proto_rawDesc), len(file_vehicle_proto_rawDesc)))
	})
	return file_vehicle_proto_rawDescData
}

var file_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_vehicle_proto_goTypes = []any{
	(*ControlReq)(nil),        // 0: vehicle.ControlReq
	(*ControlResp)(nil),       // 1: vehicle.ControlResp
	(*VehicleStatusResp)(nil), // 2: vehicle.VehicleStatusResp
	(*Request)(nil),           // 3: vehicle.Request
	(*Response)(nil),          // 4: vehicle.Response
}
var file_vehicle_proto_depIdxs = []int32{
	0, // 0: vehicle.VehicleService.ControlVehicle:input_type -> vehicle.ControlReq
	0, // 1: vehicle.VehicleService.GetVehicleStatus:input_type -> vehicle.ControlReq
	3, // 2: vehicle.Vehicle.Ping:input_type -> vehicle.Request
	1, // 3: vehicle.VehicleService.ControlVehicle:output_type -> vehicle.ControlResp
	2, // 4: vehicle.VehicleService.GetVehicleStatus:output_type -> vehicle.VehicleStatusResp
	4, // 5: vehicle.Vehicle.Ping:output_type -> vehicle.Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vehicle_proto_init() }
func file_vehicle_proto_init() {
	if File_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vehicle_proto_rawDesc), len(file_vehicle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_vehicle_proto_goTypes,
		DependencyIndexes: file_vehicle_proto_depIdxs,
		MessageInfos:      file_vehicle_proto_msgTypes,
	}.Build()
	File_vehicle_proto = out.File
	file_vehicle_proto_goTypes = nil
	file_vehicle_proto_depIdxs = nil
}
