// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: vehicle.proto

package vehicleclient

import (
	"context"

	"vehicle/vehicle"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = vehicle.Request
	Response = vehicle.Response

	Vehicle interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultVehicle struct {
		cli zrpc.Client
	}
)

func NewVehicle(cli zrpc.Client) Vehicle {
	return &defaultVehicle{
		cli: cli,
	}
}

func (m *defaultVehicle) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := vehicle.NewVehicleClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
