// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type EmqxAclReq struct {
	ClientId string `json:"clientid"` // 客户端ID，如 mobile_user123
	Username string `json:"username"` // 用户名
	Action   string `json:"action"`   // 操作类型：publish 或 subscribe
	Topic    string `json:"topic"`    // 操作的 Topic，如 /vehicle/1001/status
}

type EmqxAclResp struct {
	Result string `json:"result"` // 鉴权结果：allow 或 deny
}
