// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type VehicleControlReq struct {
	VehicleID string `json:"vehicleID,validate=min=1"` // 车辆唯一标识
	Action    string `json:"action,validate=required"` // 动作：unlock_door, lock_door, start_engine
}

type VehicleControlResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
