// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: vehicle.proto

package vehicleservice

import (
	"context"

	"vehicle/pb/vehicle"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ControlReq        = vehicle.ControlReq
	ControlResp       = vehicle.ControlResp
	Request           = vehicle.Request
	Response          = vehicle.Response
	VehicleStatusResp = vehicle.VehicleStatusResp

	VehicleService interface {
		// 接收云端下发的控制指令
		ControlVehicle(ctx context.Context, in *ControlReq, opts ...grpc.CallOption) (*ControlResp, error)
		// 供其他服务查询车辆实时状态
		GetVehicleStatus(ctx context.Context, in *ControlReq, opts ...grpc.CallOption) (*VehicleStatusResp, error)
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultVehicleService struct {
		cli zrpc.Client
	}
)

func NewVehicleService(cli zrpc.Client) VehicleService {
	return &defaultVehicleService{
		cli: cli,
	}
}

// 接收云端下发的控制指令
func (m *defaultVehicleService) ControlVehicle(ctx context.Context, in *ControlReq, opts ...grpc.CallOption) (*ControlResp, error) {
	client := vehicle.NewVehicleServiceClient(m.cli.Conn())
	return client.ControlVehicle(ctx, in, opts...)
}

// 供其他服务查询车辆实时状态
func (m *defaultVehicleService) GetVehicleStatus(ctx context.Context, in *ControlReq, opts ...grpc.CallOption) (*VehicleStatusResp, error) {
	client := vehicle.NewVehicleServiceClient(m.cli.Conn())
	return client.GetVehicleStatus(ctx, in, opts...)
}

func (m *defaultVehicleService) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := vehicle.NewVehicleServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
