// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	vehicle "mobile/internal/handler/vehicle"
	"mobile/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/vehicle/control",
				Handler: vehicle.ControlVehicleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
